### ISSUE TITLE
Null Pointer on PR create - validation only build

### ISSUE THREAD

**Issue by buggyb12** [aesanch2/salesforce-migration-assistant#7]
Sending build status INPROGRESS for commit 97582dbfdba41ce078999d50dc5813634c182e50 to BitBucket is done!
java.lang.NullPointerException
at org.jenkinsci.plugins.sma.SMARunner.(SMARunner.java:71)
at org.jenkinsci.plugins.sma.SMABuilder.perform(SMABuilder.java:65)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
at hudson.model.Build$BuildExecution.build(Build.java:205)
at hudson.model.Build$BuildExecution.doRun(Build.java:162)
at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
at hudson.model.Run.execute(Run.java:1720)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:401)

Build step 'Salesforce Migration Assistant' marked build as failure
Sending build status FAILED for commit 97582dbfdba41ce078999d50dc5813634c182e50 to BitBucket is done!
Finished: FAILURE

**Comment by aesanch2** [comment]
@buggyb12 this should be resolved with 2.2.3.

**Comment by karthikeyan68** [comment]
Hi,
i too have similar error. when is the 2.2.3 release?
