### ISSUE TITLE
Salesforce Migration Assistant Plugin Issue

### ISSUE THREAD

**Issue by shuvo1016** [aesanch2/salesforce-migration-assistant#8]
Getting below error while deploying changes between two commits in Salesforce Dev Org using Salesforce Migration Assistant Plugin in Jenkins. Any idea what could be the reason for this issue? Thanks

java.lang.NullPointerException
	at org.jenkinsci.plugins.sma.SMARunner.<init>(SMARunner.java:71)
	at org.jenkinsci.plugins.sma.SMABuilder.perform(SMABuilder.java:65)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)

Build step 'Salesforce Migration Assistant' marked build as failure
Sending e-mails to: XXX
Finished: FAILURE

**Comment by AshwiniChowdavarapu** [comment]
Hi ! I am facing the same issue, Could you please let me know the resolution for this:
07:30:07  > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
07:30:07  > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
07:30:07 Checking out Revision 5985ef898194cd4e84b5ae5fdbb053dbe78b5bac (refs/remotes/origin/master)
07:30:07  > git config core.sparsecheckout # timeout=10
07:30:07  > git checkout -f 5985ef898194cd4e84b5ae5fdbb053dbe78b5bac
07:30:08  > git rev-list 4264f572104de9eaa3863512ce5ee1a8aa5656ec # timeout=10
07:30:08 java.lang.NullPointerException
07:30:08 	at org.jenkinsci.plugins.sma.SMARunner.<init>(SMARunner.java:71)
07:30:08 	at org.jenkinsci.plugins.sma.SMABuilder.perform(SMABuilder.java:65)
07:30:08 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
07:30:08 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
07:30:08 	at hudson.model.Build$BuildExecution.build(Build.java:205)
07:30:08 	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
07:30:08 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
07:30:08 	at hudson.model.Run.execute(Run.java:1728)
07:30:08 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
07:30:08 	at hudson.model.ResourceController.execute(ResourceController.java:98)
07:30:08 	at hudson.model.Executor.run(Executor.java:404)
07:30:08 
07:30:08 Build step 'Salesforce Migration Assistant' marked build as failure

**Comment by sisira6** [comment]
Hi.. I am facing the similar kind of issue. Can anyone help in resolving this:
 > C:\Users\Sisira Kosuri\GitBash\bin\git.exe rev-list --no-walk 5123c9233c9578c19ad147e1880617cc3476e473 # timeout=10
java.lang.NullPointerException
	at org.jenkinsci.plugins.sma.SMARunner.<init>(SMARunner.java:71)
	at org.jenkinsci.plugins.sma.SMABuilder.perform(SMABuilder.java:65)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1819)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

Build step 'Salesforce Migration Assistant' marked build as failure
Finished: FAILURE
